In [2]:
# Pustovit_pr_номер.ipynb

import numpy as np

# Завдання 1
# Створіть одновимірний масив (вектор) з сумами добутків двох попередніх чисел та їхнього суми, починаючи з 1
vector_1 = [1]
for i in range(1, 10):
    value = vector_1[i-1] + vector_1[i-1] * (vector_1[i-1] + 1)
    vector_1.append(value)
vector_1 = np.array(vector_1)
print("Завдання 1:", vector_1)

# Завдання 2
# Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його випадковими цілими числами від -10 до 10
matrix_2 = np.random.randint(-10, 11, (3, 3))
print("Завдання 2:\n", matrix_2)

# Завдання 3
# Створіть масив 5x5, заповніть його випадковими дійсними числами від 0 до 1 та знайдіть відсоток чисел, які є простими
matrix_3 = np.random.rand(5, 5)
is_prime = np.vectorize(lambda x: all(x % i != 0 for i in range(2, int(np.sqrt(x)) + 1)) if x > 1 else False)
scaled_matrix = (matrix_3 * 100).astype(int)
prime_flags = is_prime(scaled_matrix)
prime_percentage = np.mean(prime_flags) * 100
print("Завдання 3: Відсоток простих чисел:", prime_percentage, "%")

# Завдання 4
# Створіть масив 3x3, заповніть його випадковими дійсними числами в діапазоні від -1.1 до 1.1 та виведіть його значення
matrix_4 = np.random.uniform(-1.1, 1.1, (3, 3))
print("Завдання 4:\n", matrix_4)

# Завдання 5
# Створіть два одновимірних масиви розміром 4, заповніть їх випадковими цілими числами в діапазоні від 15 до 25 та виконайте поелементні операції
array_5_1 = np.random.randint(15, 26, 4)
array_5_2 = np.random.randint(15, 26, 4)
sum_arrays = array_5_1 + array_5_2
diff_arrays = array_5_1 - array_5_2
mult_arrays = array_5_1 * array_5_2
print("Завдання 5:\nСума:", sum_arrays, "\nРізниця:", diff_arrays, "\nДобуток:", mult_arrays)

# Завдання 6
# Створіть дві матриці 3x3, заповніть їх цілими числами від 1 до 10 та знайдіть їх добуток
matrix_6_1 = np.random.randint(1, 11, (3, 3))
matrix_6_2 = np.random.randint(1, 11, (3, 3))
matrix_mult = np.dot(matrix_6_1, matrix_6_2)
print("Завдання 6:\n", matrix_mult)

# Завдання 7
# Створіть дві матриці 2x3 та 3x3, заповніть їх випадковими цілими числами від 1 до 5 та перемножте їх
matrix_7_1 = np.random.randint(1, 6, (2, 3))
matrix_7_2 = np.random.randint(1, 6, (3, 3))
matrix_7_mult = np.dot(matrix_7_1, matrix_7_2)
print("Завдання 7:\n", matrix_7_mult)

# Завдання 8
# Створіть матрицю 2x2, заповніть її цілими числами від 1 до 7 та знайдіть її обернену
matrix_8 = np.random.randint(1, 8, (2, 2))
inverse_matrix = np.linalg.inv(matrix_8)
print("Завдання 8:\n", inverse_matrix)

# Завдання 9
# Створіть матрицю 3x3, заповніть її дійсними числами в діапазоні від 5 до 10 та транспонуйте її
matrix_9 = np.random.uniform(5, 10, (3, 3))
transposed_matrix = matrix_9.T
print("Завдання 9:\n", transposed_matrix)

# Завдання 10
# Створіть матрицю 3x4 та вектор 4x1, заповніть їх випадковими дійсними числами від 0 до 1, та знайдіть добуток
matrix_10 = np.random.rand(3, 4)
vector_10 = np.random.rand(4, 1)
matrix_vector_mult = np.dot(matrix_10, vector_10)
print("Завдання 10:\n", matrix_vector_mult)

# Завдання 11
# Створіть матрицю 2x3 та вектор 3x1, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть добуток
matrix_11 = np.random.randint(1, 11, (2, 3))
vector_11 = np.random.randint(1, 11, (3, 1))
matrix_vector_mult_11 = np.dot(matrix_11, vector_11)
print("Завдання 11:\n", matrix_vector_mult_11)

# Завдання 12
# Створіть дві матриці 2x2, заповніть їх цілими числами від -2 до 2 та знайдіть суму всіх елементів обох матриць
matrix_12_1 = np.random.randint(-2, 3, (2, 2))
matrix_12_2 = np.random.randint(-2, 3, (2, 2))
sum_matrices = np.sum(matrix_12_1) + np.sum(matrix_12_2)
print("Завдання 12: Сума елементів:", sum_matrices)

# Завдання 13
# Створіть дві матриці 3x3, заповніть їх дійсними числами в діапазоні від 0 до 1 та знайдіть суму їх елементів
matrix_13_1 = np.random.rand(3, 3)
matrix_13_2 = np.random.rand(3, 3)
sum_elements = np.sum(matrix_13_1) + np.sum(matrix_13_2)
print("Завдання 13: Сума елементів:", sum_elements)

# Завдання 14
# Створіть матрицю 3x3, заповніть її цілими числами від 1 до 10 та знайдіть середнє значення елементів на головній діагоналі
matrix_14 = np.random.randint(1, 11, (3, 3))
diagonal_avg = np.mean(np.diag(matrix_14))
print("Завдання 14: Середнє значення на діагоналі:", diagonal_avg)

# Завдання 15
# Створіть матрицю 3x3, заповніть її дійсними числами від 0 до 1 та знайдіть вектор-стовпчик, що містить найбільший елемент у кожному стовпці
matrix_15 = np.random.rand(3, 3)
max_in_columns = np.max(matrix_15, axis=0)
print("Завдання 15: Вектор-стовпчик з максимальними елементами:", max_in_columns)


Завдання 1: [1 3 15 255 65535 4294967295 18446744073709551615
 340282366920938463463374607431768211455
 115792089237316195423570985008687907853269984665640564039457584007913129639935
 13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095]
Завдання 2:
 [[-10  -2  -7]
 [  0   9   5]
 [  5  -7   6]]
Завдання 3: Відсоток простих чисел: 36.0 %
Завдання 4:
 [[-0.80438312 -0.69132228  0.27126374]
 [ 0.82731637  1.07286438  0.78897451]
 [ 1.06984986 -0.68389237 -0.65167499]]
Завдання 5:
Сума: [35 35 44 34] 
Різниця: [ 1 -3 -2 -2] 
Добуток: [306 304 483 288]
Завдання 6:
 [[ 62  34  96]
 [118  56 168]
 [ 90  63 118]]
Завдання 7:
 [[11 31 19]
 [ 8 16 10]]
Завдання 8:
 [[-0.33333333  0.22222222]
 [ 0.33333333 -0.05555556]]
Завдання 9:
 [[8.61754107 6.28914978 9.67828575]
 [9.27153059 9.80429949 9.55531123]
 [7.00144733 8.76159897 8.88924323]]
Завдання 10:
 [[0.63443693]
 [0.84183475]
 [0.44353355]